apiVersion: apps/15
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: todo
        image: akiran0593/todo:v1
        ports:
        - containerPort: 8000
